# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# email: sano@ueda.info.waseda.ac.jp

title: J.Sano
description: >- # this means to ignore newlines until "baseurl:"
  A software developer interested in design and implementation of programming languages, 
  living in Tokyo, Japan.
  All my posts are my own and should never be taken seriously.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://sano-jin.github.io/blog/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sano_jn
github_username: sano-jin
author: sano

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

show_excerpts: true
about_author: about_author

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# paginate: 5
# paginate_path: "/blog/page:num"

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       author: "Author Name"
#       layout: post
#       hero_image: /path/to/hero-image.jpg
#       show_sidebar: true

google_analytics: "G-7DP65677HQ"

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:day/:title.html
# permalink: /:slugified_categories/:year/:month/:day/:title/

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  # offset: 2
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

kramdown:
  header_offset: 1
  # highlighter: rouge
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true
